# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87bfa4eefef168ac7fd02188955fa0c49a739329c15cca57a5d7e341a2761d2b91f19ad7e5c5b3cd9d2c7153631b44a9301a94624845de767a6d594f2cea87fc

test:
  secret_key_base: cba7c723c18b3dafcd3dd72cb68662e1b81ef841147bd409edcfb3e898ec897f3d365fdcbbe08f1d5a200103da2045f0640bff48126601260c69a24e1a91dfad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
